//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankingPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Beneficiary
    {
        public long AccountNumber { get; set; }
        public string BeneficiaryName { get; set; }
        public long BeneficiaryAcc { get; set; }
        public int Id { get; set; }
    }
}
